<?php

namespace FormForge\Components;

use Closure;
use Illuminate\Support\Str;
use Illuminate\View\View;
use ReflectionClass;

/**
 * Represents a html field to be generated by FormBuilder. It's a base class for more specific types of fields.
 *
 * @author Damian Ułan <damian.ulan@protonmail.com>
 * @copyright 2024
 */
abstract class ForgeComponent
{
    public string $name;

    public string $type;

    public ?string $value = null;

    public ?string $template = null;

    public ?string $label = null;

    public ?string $placeholder = null;

    public ?string $key = null;

    public array $classes = array();

    public bool $required = false;

    public bool $disabled = false;

    public bool $readonly = false;

    public bool $show = true;

    public string $autocomplete = '';

    public array $infos = array();

    public array $dangers = array();

    /**
     * Renders the html representation of the Component.
     */
    public function render(): View
    {
        $template = $this->template ?? Str::lower((new ReflectionClass($this))->getShortName());

        return view('formforge::components.' . $template, array(
            'component' => $this,
            'classes' => $this->getClasses(),
        ));
    }

    /**
     * Labels an Component as a required. This is not validation, only invokes visual effect.
     */
    public function required(?Closure $condition = null): static
    {
        $this->required = true;
        if (! is_null($condition)) {
            $this->required = (bool) $condition();
        }

        return $this;
    }

    /**
     * Marks a Component as disabled.
     */
    public function disabled(): static
    {
        $this->disabled = true;

        return $this;
    }

    /**
     * Marks an Component as disabled.
     */
    public function readonly(): static
    {
        $this->readonly = true;

        return $this;
    }

    /**
     * Sets html placeholder.
     */
    public function placeholder(string $text): static
    {
        $this->placeholder = empty($text) ? null : $text;

        return $this;
    }

    /**
     * Sets html default value.
     */
    public function value(string $value): static
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Sets label text for an Component.
     */
    public function label(string|callable $text): static
    {
        if (is_callable($text)) {
            $this->label = call_user_func($text);
        } else {
            $this->label = $text;
        }

        return $this;
    }

    /**
     * Add additional key that will be visible in the form as muted text.
     */
    public function key(string|callable|null $key): static
    {
        if (is_callable($key)) {
            $this->key = call_user_func($key);
        } else {
            $this->key = $key;
        }

        return $this;
    }

    /**
     * Renders input label to html.
     *
     * @return string
     */
    public function getLabel(): ?View
    {
        if (! empty($this->label) && ! empty($this->name)) {
            return view('formforge::components.label', array(
                'label' => $this->label,
                'name' => $this->name,
                'required' => $this->required,
                'key' => $this->key,
            ));
        }

        return null;
    }

    public function class(...$classes)
    {
        if (! empty($classes)) {
            foreach ($classes as $class) {
                $this->classes[] = $class;
            }
        }

        return $this;
    }

    /**
     * Generates tippy.js tooltip description for the field.
     */
    public function info(string $text): static
    {
        $this->infos[] = $text;

        return $this;
    }

    /**
     * Renders input label to html.
     *
     * @return string
     */
    public function getInfos(): ?string
    {
        if (! empty($this->infos)) {
            $output = '';
            foreach ($this->infos as $info) {
                $output .= '<span class="info-box" data-tippy-content="' . $info . '"><i class="bi-info-circle-fill"></i></span>';
            }

            return $output;
        }

        return null;
    }

    /**
     * Sets html autocomplete setting
     */
    public function autocomplete(string $type): static
    {
        $this->autocomplete = $type;

        return $this;
    }

    /**
     * Set additional conditions that need to be met for component to be shown in the form.
     *
     * @param  mixed  $callback
     */
    public function condition($callback): static
    {
        $return = $callback();
        $this->show = (bool) $return;

        return $this;
    }

    private function getClasses(): ?string
    {
        $this->classes = array_unique($this->classes);

        return empty($this->classes) ? null : implode(' ', $this->classes);
    }
}
